---
- name: install the latest version of Apache
  yum:
    name: httpd
    state: latest
- name: copy html 
  copy:
    src: /etc/ansible/roles/apache/files/index.html
    dest: /var/www/html
- name: restart httpd
  service:
    name: httpd
    state: restarted
- name: Enable httpd
  service:
    name: httpd
    enabled: yes
